src/project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    ] + urlpatterns

src/shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.ProductView.as_view(),
        name='all_products_page',
    ),
    path(
        'category/<int:category_id>/',
        views.ProductView.as_view(),
        name='product_page',
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile_page',
    ),
    path(
        'profile/edit/',
        views.ProfileEditView.as_view(),
        name='profile_edit_page',
    ),
    path(
        'cart/',
        views.CartView.as_view(),
        name='cart_page',
    ),
    path(
        'cart/add/',
        views.AddToCartView.as_view(),
        name='add_to_cart',
    ),
    path(
        'cart/clear/',
        views.ClearCartView.as_view(),
        name='clear_cart',
    ),
    path(
        'cart/order/',
        views.OrderCreateView.as_view(),
        name='create_order',
    ),
    path(
        'orders/',
        views.OrderView.as_view(),
        name='orders_page',
    ),
    path(
        'signup/',
        views.RegistrationView.as_view(),
        name='sign_up',
    ),
]

src/shop/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from phonenumber_field.modelfields import PhoneNumberField

User = get_user_model()


class ProductCategory(models.Model):
    """Model for product categories."""
    name = models.CharField(
        verbose_name=_('category name'),
        max_length=128,
    )

    def __str__(self):
        return '{} ({})'.format(self.name, self.id)

    class Meta:
        verbose_name = _('product category')
        verbose_name_plural = _('product categories')


class Product(models.Model):
    """Model for products."""
    # Or M2M here?
    category = models.ForeignKey(
        ProductCategory,
        verbose_name=_('category'),
        on_delete=models.PROTECT,
    )

    image = models.ImageField(
        verbose_name=_('image'),
        upload_to='products/',
        blank=True,
    )

    description = models.TextField(
        verbose_name=_('description'),
        blank=True,
    )

    price = models.DecimalField(
        verbose_name=_('price'),
        max_digits=10,
        decimal_places=2,
    )

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')


class Order(models.Model):
    """Model for orders."""
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )

    products = models.ManyToManyField(
        Product,
        through='OrderItem',
        through_fields=('order', 'product'),
        related_name='orders',
        # related_query_name='application',
    )

    first_name = models.CharField(
        verbose_name=_('first name'),
        max_length=150,
    )

    patronymic_name = models.CharField(
        verbose_name=_('patronymic name'),
        blank=True,
        max_length=150,
    )

    last_name = models.CharField(
        verbose_name=_('second name'),
        max_length=150,
    )

    address = models.TextField(
        verbose_name=_('address for delivery'),
    )

    phone = PhoneNumberField(
        verbose_name=_('phone number'),
        blank=True,
    )

    email = models.EmailField(
        verbose_name=_('e-mail address'),
        blank=True,
    )

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def get_full_name(self):
        """Get full name of buyer."""
        if self.patronymic_name:
            return '{} {} {}'.format(
                self.first_name,
                self.patronymic_name,
                self.last_name,
            )

        return '{} {}'.format(
            self.first_name,
            self.last_name,
        )


class OrderItem(models.Model):
    """Models fo order items."""
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT,
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.PROTECT,
    )

    quantity = models.PositiveIntegerField(
        verbose_name=_('quantity')
    )

    class Meta:
        # No two order lines with same product.
        unique_together = [
            'order',
            'product',
        ]
        verbose_name = _('order item')
        verbose_name_plural = _('order items')

src/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseRegistrationForm
from django.contrib.auth import get_user_model

from .models import Order


User = get_user_model()


class AddToCartForm(forms.Form):
    """Form to add product to cart."""
    product_id = forms.IntegerField(
        widget=forms.HiddenInput(),
    )
    quantity = forms.IntegerField(
        widget=forms.HiddenInput(),
    )


class OrderForm(forms.ModelForm):
    """For for create order from cart."""
    class Meta:
        model = Order
        fields = (
            'first_name',
            'patronymic_name',
            'last_name',
            'address',
            'phone',
            'email',
        )


class RegistrationForm(BaseRegistrationForm):
    """Form for user registrations."""
    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2',
        )


class ProfileEditForm(forms.ModelForm):
    """Form for user registrations."""
    class Meta:
        model = User
        fields = (
            'first_name',
            'patronymic_name',
            'last_name',
            'address',
            'phone',
            'email',
        )

src/shop/views.py
import logging

from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.forms import Form
from django.db import transaction
from django.views.generic import (
    TemplateView, ListView, FormView, CreateView, UpdateView
)
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme

from .models import Product, Order
from .forms import AddToCartForm, RegistrationForm, OrderForm, ProfileEditForm
from .decorators import redirect_to_http, redirect_to_https

logger = logging.getLogger(__name__)


class RedirectFieldNameMixin:
    """Mixin for redirect query field."""
    redirect_field_name = REDIRECT_FIELD_NAME

    def get_success_url(self):
        """Get success url from redirect field."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '/')
        )

        url_is_safe = url_has_allowed_host_and_scheme(
            url=redirect_to,
            allowed_hosts=(
                self.request.get_host(),
            ),
            require_https=self.request.is_secure(),
        )

        return redirect_to if url_is_safe else '/'


class RegistrationView(CreateView):
    """Registration View."""
    form_class = RegistrationForm
    template_name = 'shop/sign_up_page.html'
    success_url = reverse_lazy('profile_page')


@method_decorator(redirect_to_http, name='get')
class ProductView(ListView):
    """Production View."""
    template_name = 'shop/product_page.html'
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()

        category_id = self.kwargs.get('category_id')

        if category_id:
            queryset = queryset.filter(category__id=category_id)

        return queryset.select_related('category')


@method_decorator(redirect_to_https, name='get')
@method_decorator(login_required, name='dispatch')
class ProfileView(TemplateView):
    """Profile View."""
    template_name = 'shop/profile_page.html'


@method_decorator(redirect_to_http, name='get')
@method_decorator(login_required, name='dispatch')
class ProfileEditView(UpdateView):
    """Profile edit view."""
    template_name = 'shop/profile_edit_page.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('profile_page')

    def get_object(self, queryset=None):
        return self.request.user


class CartView(ListView):
    """Cart view."""
    template_name = 'shop/cart_page.html'
    model = Product

    def get_queryset(self):
        """Get cart from session and construct queryset with quantity."""
        queryset = super().get_queryset()

        try:
            cart = self.request.session['cart']
        except KeyError:
            cart = {}

        queryset = queryset.filter(
            id__in=cart.keys()
        ).select_related(
            'category'
        )

        # Ugly but easy.

        for item in queryset:
            item.quantity = cart[str(item.id)]

        return queryset


class AddToCartView(RedirectFieldNameMixin, FormView):
    """View for add product to view."""
    http_method_names = ['post', 'options']
    form_class = AddToCartForm

    def form_valid(self, form):
        """Process valid form."""
        # Use model form only validation and save in session instead of db.
        # This is simplest way to make it. Of course in the real world
        # we should use models like Cart and CartItem.

        self.save_product_in_cart(
            form.cleaned_data['product_id'],
            form.cleaned_data['quantity'],
        )

        logger.debug(
            'AddToCartView.form_valid %r, %r',
            form.cleaned_data,
            self.request.session,
        )

        return super().form_valid(form)

    def form_invalid(self, form):
        """Process invalid form."""
        # Doing as valid. Silence is golden :)
        logger.warning('AddToCartView.form_invalid %r', form.errors)
        return super().form_valid(form)

    def save_product_in_cart(self, product_id, quantity):
        """Save product in session."""
        try:
            cart = self.request.session['cart']
        except KeyError:
            cart = {}

        # Serializer of session works correctly only with str.
        product_id = str(product_id)

        try:
            cart[product_id] += quantity
        except KeyError:
            cart[product_id] = quantity

        self.request.session['cart'] = cart


class ClearCartView(RedirectFieldNameMixin, FormView):
    """View to clear cart."""
    http_method_names = ['post', 'options']
    form_class = Form

    def form_valid(self, form):
        """Process valid form."""
        self.request.session['cart'] = {}
        return super().form_valid(form)

    def form_invalid(self, form):
        """Process invalid form."""
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class OrderCreateView(CreateView):
    """View for create order from cart."""
    template_name = 'shop/create_order_page.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders_page')

    def get_initial(self):
        """Return the initial data from user profile."""
        initial = super().get_initial()

        initial.update(
            self.request.user.get_for_checkout()
        )

        return initial

    def clear_cart(self):
        """Clear cart."""
        self.request.session['cart'] = {}

    @transaction.atomic
    def form_valid(self, form):
        """Process valid form."""
        order = form.save(commit=False)
        order.user = self.request.user
        order.save()

        try:
            cart = self.request.session['cart']
        except KeyError:
            # TODO: Does cart is empty?
            return super().form_valid(form)

        for product_id, quantity in cart.items():
            order.orderitem_set.create(
                product_id=product_id,
                quantity=quantity,
            )

        # Clear cart on commit
        transaction.on_commit(lambda: self.clear_cart())

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class OrderView(ListView):
    """View for order list."""
    template_name = 'shop/orders_page.html'
    model = Order

    def get_queryset(self):
        """Get queryset of orders."""
        queryset = super().get_queryset()

        queryset = queryset.filter(
            user=self.request.user
        ).select_related(
            'user',
        )

        return queryset

src/shop/templates/shop/_add_to_cart_form.html
{% load i18n %}
<form action="{% url 'add_to_cart' %}?next={{ next }}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="card-link btn btn-primary" value="{% trans 'Buy' %}">
</form>

src/shop/templates/shop/_product_category_menu.html
<ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'all_products_page' %}">All categories</a>
    </li>
    {% for category in category_list %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'product_page' category.id %}">{{ category.name }}</a>
    </li>
    {% endfor %}
</ul>

src/shop/templates/shop/cart_page.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
    {% trans 'Cart' %}
{% endblock %}

{% block header %}
    <h1>{% trans 'Cart' %}</h1>
{% endblock %}

{% block content %}
    {% if product_list %}
    <div class="row">
        <table class="table col table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Description' %}</th>
                    <th>{% trans 'Category' %}</th>
                    <th>{% trans 'Quantity' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for product in product_list %}
                <tr>
                    <td>{{ product.description }}</td>
                    <td>{{ product.category.name }}</td>
                    <td>{{ product.quantity }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row">
        <a href="{% url 'create_order' %}" class="btn btn-primary" role="button">{% trans 'Check out' %}</a>
    </div>
    {% else %}
    <div class="row">
        <p>No items here. Add products to cart from <a href="{% url 'all_products_page' %}">catalog</a>.</p>
    </div>
    {% endif %}
{% endblock %}

src/shop/templates/shop/create_order_page.html
{% extends "base.html" %}
{% load i18n static crispy_forms_tags %}

{% block title %}
    {% trans 'Checkout' %}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row  justify-content-center">
            <form class="col-4" method="post">
                <div class="col text-center">
                    <h1 class="h3 mb-4 font-weight-normal">{% trans 'Order checkout' %}</h1>
                </div>
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Checkout' %}</button>
                <p class="mt-5 mb-3 text-center text-muted">&copy; 2020</p>
            </form>
        </div>
    </div>

{% endblock %}

src/shop/templates/shop/orders_page.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
    {% trans 'Orders' %}
{% endblock %}

{% block header %}
    <h1>{% trans 'Orders' %}</h1>
{% endblock %}

{% block content %}
    {% if order_list %}
    <div class="row">
        <table class="table col table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Id' %}</th>
                    <th>{% trans 'Full name' %}</th>
                    <th>{% trans 'Delivery address' %}</th>
                    <th>{% trans 'E-mail' %}</th>
                    <th>{% trans 'Phone' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for order in order_list %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.get_full_name }}</td>
                    <td>{{ order.address }}</td>
                    <td>{{ order.email }}</td>
                    <td>{{ order.phone }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="row">
        <p>{% trans 'No orders here.' %}</p>
    </div>
    {% endif %}
{% endblock %}

src/shop/templates/shop/product_page.html
{% extends "base.html" %}
{% load i18n static shop_tags %}

{% block title %}
    {% trans 'Catalog' %}
{% endblock %}

{% block header %}
    <h1 class="col">{% trans 'Catalog' %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        {% for product in product_list %}
        <div class="col-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <img class="card-img-top" src="{{ MEDIA_PREFIX }}{{ product.image.url }}" alt="...">
                    <h5 class="card-title mb-2">Category: {{ product.category.name }}</h6>
                    <h6 class="card-title mb-2">Price: ${{ product.price }}</h6>
                    <p class="card-text">{{ product.description }}</p>
                    {% add_to_cart_form product.id 1 %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

src/shop/templates/shop/profile_edit_page.html
{% extends "base.html" %}
{% load i18n static crispy_forms_tags %}

{% block title %}
    {% trans 'Edit profile' %}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row  justify-content-center">
            <form class="col-4" method="post">
                <div class="col text-center">
                    <h1 class="h3 mb-4 font-weight-normal">{% trans 'Edit profile' %}</h1>
                </div>
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Save' %}</button>
            </form>
        </div>
    </div>

{% endblock %}

src/shop/templates/shop/profile_page.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    {% trans 'Profile' %}
{% endblock %}

{% block header %}
    <h1 class="col">{% trans 'Your profile' %}</h1>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <table class="col-5">
                <thead>
                    <tr></tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Username:</th>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <th scope="row">E-mail:</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Phone:</th>
                        <td>{{ user.phone }}</td>
                    </tr>
                    <tr>
                        <th scope="row">First name:</th>
                        <td>{{ user.first_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Patronymic name:</th>
                        <td>{{ user.patronymic_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Second name:</th>
                        <td>{{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Address:</th>
                        <td>{{ user.address }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row mt-3">
            <a href="{% url 'profile_edit_page' %}" class="btn btn-primary">{% trans 'Edit profile' %}</a>
        </div>
    </div>
{% endblock %}

src/shop/templates/shop/sign_up_page.html
{% extends "base.html" %}
{% load i18n static crispy_forms_tags %}

{% block title %}
    {% trans 'Sign up' %}
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row  justify-content-center">
            <form class="col-4" method="post">
                <div class="col text-center">
                    <h1 class="h3 mb-4 font-weight-normal">{% trans 'Sign up' %}</h1>
                </div>
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Sign up' %}</button>
                <p class="mt-5 mb-3 text-center text-muted">&copy; 2020</p>
            </form>
        </div>
    </div>

{% endblock %}